import {
  web,
  mobile,
  backend,
  creator,
  Cricket,
  Football,
  Athletics,
  Badminton,
  Basketball,
  TableTennis,
  LawnTennis,
  VolleyBall,
  Kabaddi,
  Hockey,
  Squash,
  BGMI,
  Valo,
  ClashRoyale,
} from "../assets";

import {
  Abhishek2,
  Ankush,
  Anup,
  Aryan,
  BD,
  Buddhav,
  Chinmay,
  Dheeraj,
  Abhishek,
  Dhruv,
  Gyani,
  Kamal,
  Kowshika,
  Krushnai,
  Mohanshi,
  Naveen,
  Palak,
  Poras,
  PraveenOla,
  Pritam,
  Priyansh,
  Pujit,
  Rathod,
  Ravindra,
  Rishi,
  Sanjeet,
  Saroj,
  Sashwat,
  Tushar,
  Vishal,
  Saurabh,
  Prateek,
  Kuldeep,
  Prince,
  Barwar,
  Shivangi
} from "../assets/team";

import { chess } from "../assets";
import { Linkedin } from "lucide-react";

export const Teamdata = [
  {
    title: "1",
    imgPath: Kuldeep,
    Name: "Kuldeep",
    Designation: "Festival Chief",
    instaLink: "https://www.instagram.com/varchas_iitj/",
    linkedIn: "https://www.linkedin.com/in/varchas-inter-college-sports-fest-of-iit-jodhpur-802b4b233/"
  },
  {
    title: "2",
    imgPath: Prateek,
    Name: "Prateek Kumar",
    Designation: "Festival Chief",
    instaLink: "https://www.instagram.com/prateek_kumar_15/",
    linkedIn: "https://www.linkedin.com/in/prateek-kumar-m07-d15-y2003/"
  },
  {
    title: "3",
    imgPath: Prince,
    Name: "Prince",
    Designation: "Festival Chief",
    instaLink: "https://www.instagram.com/_choudhary1028/",
    linkedIn: "https://www.linkedin.com/in/prince-chaudhary-117338259/"
  },
  {
    title: "4",
    imgPath: Barwar,
    Name: "Harshit Barwar",
    Designation: "Festival Chief",
    instaLink: "https://www.instagram.com/harshit_barwar/",
    linkedIn: "https://www.linkedin.com/in/harshit-barwar-aab443304/"
  },
  {
    title: "5",
    imgPath: Saurabh,
    Name: "Saurabh Rajmane",
    Designation: "Web Development",
    instaLink: "https://www.instagram.com/Saurabh.r23/",
    linkedIn: "https://www.linkedin.com/in/saurabh-rajmane-a67b5226b/"
  },
  {
    title: "6",
    imgPath: Chinmay,
    Name: "Chinmay",
    Designation: "Web Development",
    instaLink: "https://www.instagram.com/chinmayvashishth/",
    linkedIn: "https://www.linkedin.com/in/chinmay-vashishth-1a41271b0/"
  },
  {
    title: "7",
    imgPath: Rathod,
    Name: "Aditya Rathor",
    Designation: "Web Development",
    instaLink: "",
    linkedIn: "https://www.linkedin.com/in/aditya-rathor-87829324b/"
  },
  {
    title: "8",
    imgPath: BD,
    Name: "Bhavyadeep",
    Designation: "Marketing",
    instaLink: "https://www.instagram.com/bhavya_passive/",
    linkedIn: "https://www.linkedin.com/in/bhavyadeep-hada-b07a7516a/"
  },
  {
    title: "9",
    imgPath: Aryan,
    Name: "Aryan Sharma",
    Designation: "Marketing",
    instaLink: "https://www.instagram.com/__aryan_shhh/",
    linkedIn: "https://www.linkedin.com/in/aryan-sharma-b642b0258/"
  },
  {
    title: "10",
    imgPath: PraveenOla,
    Name: "Praveen",
    Designation: "Marketing",
    instaLink: "https://www.instagram.com/praveen.ola/",
    linkedIn: "https://www.linkedin.com/in/praveen-ola-991a66256/"
  },
  {
    title: "11",
    imgPath: Rishi,
    Name: "Rishi Yadav",
    Designation: "Marketing",
    instaLink: "",
    linkedIn: "https://www.linkedin.com/in/rishiyadav07/"
  },
  {
    title: "12",
    imgPath: Vishal,
    Name: "Vishal",
    Designation: "Publicity & Media",
    instaLink: "https://www.instagram.com/vishal_meena.7/",
    linkedIn: "https://www.linkedin.com/in/vishal-meena-a93761256/"
  },
  {
    title: "13",
    imgPath: Ravindra,
    Name: "Ravindar",
    Designation: "Publicity & Media",
    instaLink: "https://www.instagram.com/_ravindar.naik_/",
    linkedIn: "https://www.linkedin.com/in/azmeera-ravindar-naik-585a21256/"
  },
  {
    title: "14",
    imgPath: Dheeraj,
    Name: "Dheeraj",
    Designation: "Publicity & Media",
    instaLink: "",
    linkedIn: "https://www.linkedin.com/in/dheeraj-dhakad-9580-ok/"
  },
  {
    title: "15",
    imgPath: Sashwat,
    Name: "Shashwat",
    Designation: "Publicity & Media",
    instaLink: "https://www.instagram.com/shashwat2m/",
    linkedIn: "https://www.linkedin.com/in/shashwat-meena-ab6611256/"
  },
  {
    title: "16",
    imgPath: Naveen,
    Name: "Naveen",
    Designation: "ATS",
    instaLink: "https://www.instagram.com/__.naveen_kumar._/",
    linkedIn: "https://www.linkedin.com/in/j-naveen-kumar-a6557725a/"
  },
  {
    title: "17",
    imgPath: Mohanshi,
    Name: "Mohanshi Jain",
    Designation: "ATS",
    instaLink: "https://www.instagram.com/mohanshi.jain/",
    linkedIn: "https://www.linkedin.com/in/mohanshi-jain-9565aa288/"
  },
  {
    title: "18",
    imgPath: Poras,
    Name: "Poras",
    Designation: "ATS",
    instaLink: "https://www.instagram.com/thardak_poras/",
    linkedIn: ""
  },
  {
    title: "20",
    imgPath: Anup,
    Name: "Anup",
    Designation: "ATS",
    instaLink: "https://www.instagram.com/anupkumar_iitj/",
    linkedIn: "https://www.linkedin.com/in/anup-kumar-642100146/"
  },
  {
    title: "21",
    imgPath: Dhruv,
    Name: "Dhruv",
    Designation: "ATS",
    instaLink: "https://www.instagram.com/dhruv.shivhare_001/",
    linkedIn: "https://www.linkedin.com/in/dhruv-shivhare-a7a5a0259/"
  },
  {
    title: "22",
    imgPath: Saroj,
    Name: "Saroj",
    Designation: "Informals",
    instaLink: "https://www.instagram.com/sarojkr__/",
    linkedIn: "https://www.linkedin.com/in/saroj-kumar-65736b25a/"
  },
  {
    title: "23",
    imgPath: Palak,
    Name: "Palak",
    Designation: "Informals",
    instaLink: "https://www.instagram.com/palakkbhawsar/",
    linkedIn: "https://www.linkedin.com/in/palak-bhawsar-a77436262/"
  },

  {
    title: "24",
    imgPath: Abhishek,
    Name: "Abhishek",
    Designation: "Informals",
    instaLink: "",
    linkedIn: ""
  },
  {
    title: "25",
    imgPath: Kamal,
    Name: "kamal",
    Designation: "Design & Creativity",
    instaLink:"",
    linkedIn: "https://www.linkedin.com/in/kamal-aietaan-684b88258/"
  },
  {
    title: "26",
    imgPath: Kamal,
    Name: "Vighnesh",
    Designation: "Design & Creativity",
    instaLink:"https://www.instagram.com/vighumandy/",
    linkedIn: "https://www.linkedin.com/in/vighnesh-mandavkar-3103b8254/"
  },
  {
    title: "27",
    imgPath: Buddhav,
    Name: "Buddhav Garg",
    Designation: "Design & Creativity",
    instaLink: "https://www.instagram.com/buddhav_04/",
    linkedIn: "https://www.linkedin.com/in/buddhav-garg/"
  },
  {
    title: "28",
    imgPath: Shivangi,
    Name: "Shivangi Mehra",
    Designation: "Design & Creativity",
    instaLink: "https://www.instagram.com/poppythephool/",
    linkedIn: "https://www.linkedin.com/in/shivangi-mehra-79048a256/"
  },
  {
    title: "29",
    imgPath: Ankush,
    Name: "Ankush",
    Designation: "Sports",
    instaLink: "https://www.instagram.com/_.ankush._05/",
    linkedIn: "https://www.linkedin.com/in/ankush-choudhary-915261260/"
  },
  {
    title: "30",
    imgPath: Pujit,
    Name: "Pujit",
    Designation: "Sports",
    instaLink: "https://www.instagram.com/shirley_itsaboobjob/",
    linkedIn: "https://www.linkedin.com/in/pujit-jha-a10aa0258/"
  },
  {
    title: "31",
    imgPath: Sanjeet,
    Name: "Sanjeet",
    Designation: "Sports",
    instaLink: "https://www.instagram.com/sanjeetathawale/",
    linkedIn: "https://www.linkedin.com/in/sanjeet-athawale/"
  },
  {
    title: "32",
    imgPath: Abhishek,
    Name: "Abhishek Yadav",
    Designation: "Sports",
    instaLink: "",
    linkedIn: ""
  },
  {
    title: "33",
    imgPath: Priyansh,
    Name: "Priyansh",
    Designation: "Sports",
    instaLink: "https://www.instagram.com/priyansh_star07/",
    linkedIn: "https://www.linkedin.com/in/priyansh-bhavsar-2b4b95260/"
  },
  {
    title: "34",
    imgPath: Gyani,
    Name: "Gyanendra ",
    Designation: "Resources",
    instaLink: "https://www.instagram.com/gyanendra_bhardwaj910/",
    linkedIn: "https://www.linkedin.com/in/gyanendra-bhardwaj-451292250/"
  },
  {
    title: "35",
    imgPath: Tushar,
    Name: "Tushar",
    Designation: "Resources",
    instaLink: "https://www.instagram.com/tushar_kumar85/",
    linkedIn: "https://www.linkedin.com/in/tushar-kumar-0195b3256/"
  },
  {
    title: "36",
    imgPath: Pritam,
    Name: "Preetam",
    Designation: "Public Relations",
    instaLink: "https://www.instagram.com/pkumar_skr77/",
    linkedIn: "https://www.linkedin.com/in/preetam-jaat-060042259/"
  },
  {
    title: "37",
    imgPath: Kowshika,
    Name: "Kowshika",
    Designation: "Public Relations",
    instaLink: "https://www.instagram.com/kowshika_raj_/",
    linkedIn: "https://www.linkedin.com/in/sri-kowshika-raj-banoth/"
  },
  {
    title: "38",
    imgPath: Krushnai,
    Name: "Krushnai",
    Designation: "Public Relations",
    instaLink: "",
    linkedIn: ""
  },
  {
    title: "39",
    imgPath: Kamal,
    Name: "Kamal",
    Designation: "Public Relations",
    instaLink: "",
    linkedIn: "https://www.linkedin.com/in/kamal-kumar-009a0a256/"
  },
  
];

const events = [
  {
    id: "1",
    title: "Athletics",
    icon: Athletics,
    category: " M / W",
    team: "solo",
    registerPath: "/create",
    detailsPath : "/athletics",
    rulebook : "https://www.canva.com/design/DAFwNvDQjw0/5g9BG60T6QKiz8GzfbBOzg/view?utm_content=DAFwNvDQjw0&utm_campaign=designshare&utm_medium=link&utm_source=publishsharelink"
  },
  {
    id: "2",
    title: "Badminton",
    icon: Badminton,
    category: " M / W",
    team: "solo",
    registerPath: "/create",
    detailsPath : "/badminton",
    rulebook : "https://www.canva.com/design/DAFwNS9hnVc/WWTBdlP0w7ynDKjZGB3YlA/view?utm_content=DAFwNS9hnVc&utm_campaign=designshare&utm_medium=link&utm_source=publishsharelink"
  },
  {
    id: "3",
    title: "Basketball",
    icon: Basketball,
    category: " M / W",
    team: "team",
    registerPath: "/create",
    detailsPath : "/basketball",
    rulebook : "https://www.canva.com/design/DAFwNlu02xQ/Ba6SbquTIelw9KBQtRVhRA/view?utm_content=DAFwNlu02xQ&utm_campaign=designshare&utm_medium=link&utm_source=publishsharelink"
  },
  {
    id: "4",
    title: "Cricket",
    icon: Cricket,
    category: " M / W",
    team: "team",
    registerPath: "/create",
    detailsPath : "/cricket",
    rulebook : "https://www.canva.com/design/DAFwNcg45lM/UumJx7LHSimuECQYe6qznA/view?utm_content=DAFwNcg45lM&utm_campaign=designshare&utm_medium=link&utm_source=publishsharelink"
  },
  {
    id: "5",
    title: "Football",
    icon: Football,
    category: " M / W",
    team: "team",
    registerPath: "/create",
    detailsPath : "/football",
    rulebook : "https://www.canva.com/design/DAFwPHWol04/i-KCuAYW6PyybKXeShqrNA/view?utm_content=DAFwPHWol04&utm_campaign=designshare&utm_medium=link&utm_source=publishsharelink"
  },
  {
    id: "6",
    title: "Table Tennis",
    icon: TableTennis,
    category: " M / W",
    team: "Doubles / Mixed",
    registerPath: "/create",
    detailsPath : "/table-tennis",
    rulebook : "https://www.canva.com/design/DAFwOL5vgac/LG3YCOM_jtFJMTpRK4WNQg/view?utm_content=DAFwOL5vgac&utm_campaign=designshare&utm_medium=link&utm_source=publishsharelink"
  },
  {
    id: "7",
    title: "Lawn Tennis",
    icon: LawnTennis,
    category: " M / W",
    team: "doubles / mixed",
    registerPath: "/create",
    detailsPath : "/lawn-tennis",
    rulebook : "https://www.canva.com/design/DAFwN9PrY0M/DjVxBpukTD-iKoNh54tnJA/view?utm_content=DAFwN9PrY0M&utm_campaign=designshare&utm_medium=link&utm_source=publishsharelink"
  },
  {
    id: "8",
    title: "Volleyball",
    icon: VolleyBall,
    category: " M / W",
    team: "team",
    registerPath: "/create",
    detailsPath : "/volleeyball",
    rulebook : "https://www.canva.com/design/DAFwN3YUlYY/G8f8edC8rzm3wN5x54215A/view?utm_content=DAFwN3YUlYY&utm_campaign=designshare&utm_medium=link&utm_source=publishsharelink"
  },
  {
    id: "9",
    title: "Kabaddi",
    icon: Kabaddi,
    category: " M / W",
    team: "team",
    registerPath: "/create",
    detailsPath : "/kabaddi",
    rulebook : "https://www.canva.com/design/DAFwNZ5Wihs/fxsMfxLEanzI_AS7ficNsQ/view?utm_content=DAFwNZ5Wihs&utm_campaign=designshare&utm_medium=link&utm_source=publishsharelink"
  },
  {
    id: "10",
    title: "Hockey",
    icon: Hockey,
    category: " M / W",
    team: "team",
    registerPath: "/create",
    detailsPath : "/hockey",
    rulebook : "https://www.canva.com/design/DAFwNXk87gY/vb2mmez9SfX9xUQVoxD2vQ/view?utm_content=DAFwNXk87gY&utm_campaign=designshare&utm_medium=link&utm_source=publishsharelink"
  },
  {
    id: "11",
    title: "Squash",
    icon: Squash,
    category: " M / W",
    team: "team",
    registerPath: "/create",
    detailsPath : "/squash",
    rulebook : "https://www.canva.com/design/DAFwOGYgma0/OuHL_yT5ruFWAyvmGS1R4w/view?utm_content=DAFwOGYgma0&utm_campaign=designshare&utm_medium=link&utm_source=publishsharelink"
  },
  {
    id: "12",
    title: "Chess",
    icon: chess,
    category: " M / W",
    team: "team",
    registerPath: "/create",
    detailsPath : "/chess",
    rulebook : "https://www.canva.com/design/DAFwNTLw2k4/lAM5K2aQMkCls_lhpTCLZQ/view?utm_content=DAFwNTLw2k4&utm_campaign=designshare&utm_medium=link&utm_source=publishsharelink"
  },
  {
    id: "13",
    title: "BGMI",
    icon: BGMI,
    category: " M / W",
    team: "team",
    registerPath: "/create",
    team_id: [
      { value: "id1", label: "id1" },
      { value: "id2", label: "id2" },
      { value: "id3", label: "id3" },
      { value: "id4", label: "id4" },
    ],
    detailsPath : "/esports/bgmi",
    rulebook : "https://www.canva.com/design/DAFwOIZ0OSw/82BAJQT_oTNrsl_X94-Kgg/view?utm_content=DAFwOIZ0OSw&utm_campaign=designshare&utm_medium=link&utm_source=publishsharelink"
  },
  {
    id: "14",
    title: "Valorant",
    icon: Valo,
    category: " M / W",
    team: "team",
    registerPath: "/create",
    team_id: [
      { value: "id1", label: "id1" },
      { value: "id2", label: "id2" },
      { value: "id3", label: "id3" },
      { value: "id4", label: "id4" },
      { value: "id5", label: "id5" },
    ],
    detailsPath : "/esports/valorant",
    rulebook : "https://www.canva.com/design/DAFwOb-QXdU/LeIzgc7nD_JQHUFfK2EL6Q/view?utm_content=DAFwOb-QXdU&utm_campaign=designshare&utm_medium=link&utm_source=publishsharelink"
  },
  {
    id: "15",
    title: "Clash Royale",
    icon: ClashRoyale,
    category: " M / W",
    team: "team",
    registerPath: "/create",
    team_id: [{ value: "id1", label: "id1" }],
    detailsPath : "/esports/clash-royale",
    rulebook : "https://www.canva.com/design/DAFwO-vD7pI/YrLYWlrlbGiwEIOAMev8XQ/view?utm_content=DAFwO-vD7pI&utm_campaign=designshare&utm_medium=link&utm_source=publishsharelink"
  },
];

const signupFields = [
  {
    labelText: "Email address",
    labelFor: "email",
    id: "email",
    name: "email",
    type: "email",
    autoComplete: "email",
    isRequired: true,
    placeholder: "Email address",
  },
  {
    labelText: "First Name",
    labelFor: "First Name",
    id: "first_name",
    name: "First Name",
    type: "text",
    autoComplete: "First Name",
    isRequired: true,
    placeholder: "First Name",
  },
  {
    labelText: "Last Name",
    labelFor: "Last Name",
    id: "last_name",
    name: "Last Name",
    type: "text",
    autoComplete: "Last Name",
    isRequired: true,
    placeholder: " Last Name",
  },
  {
    labelText: "Password",
    labelFor: "password",
    id: "password",
    name: "password",
    type: "password",
    autoComplete: "current-password",
    isRequired: true,
    placeholder: "Password",
  },
  {
    labelText: "Confirm Password",
    labelFor: "cnfpassword",
    id: "confirm_password",
    name: "cnfpassword",
    type: "password",
    autoComplete: "current-password",
    isRequired: true,
    placeholder: "Confirm Password",
  },
  {
    labelText: "gender",
    labelFor: "gender",
    id: "gender",
    name: "gender",
    type: "dropdown",
    autoComplete: "",
    isRequired: true,
    placeholder: "Gender",
    options: [
      { value: "M", label: "Male" },
      { value: "F", label: "Female" },
      { value: "T", label: "Other" },
    ],
  },
  {
    labelText: "Phone",
    labelFor: "phone",
    id: "phone",
    name: "phone",
    type: "tel",
    autoComplete: "",
    isRequired: true,
    placeholder: "+91 xxxxxxxxxx",
  },
  {
    labelText: "college",
    labelFor: "college",
    id: "college",
    name: "college",
    type: "text",
    autoComplete: "college",
    isRequired: true,
    placeholder: "College",
  },
  {
    labelText: "State",
    labelFor: "state",
    id: "state",
    name: "state",
    type: "dropdown",
    options: [
      { value: "1", label: "Andhra Pradesh" },
      { value: "2", label: "Arunachal Pradesh" },
      { value: "3", label: "Assam" },
      { value: "4", label: "Bihar" },
      { value: "5", label: "Chhattisgarh" },
      { value: "6", label: "Goa" },
      { value: "7", label: "Gujarat" },
      { value: "8", label: "Haryana" },
      { value: "9", label: "Himachal Pradesh" },
      { value: "10", label: "Jammu & Kashmir" },
      { value: "11", label: "Jharkhand" },
      { value: "12", label: "Karnataka" },
      { value: "13", label: "Kerala" },
      { value: "14", label: "Madhya Pradesh" },
      { value: "15", label: "Maharashtra" },
      { value: "16", label: "Manipur" },
      { value: "17", label: "Meghalaya" },
      { value: "18", label: "Mizoram" },
      { value: "19", label: "Nagaland" },
      { value: "20", label: "Odisha" },
      { value: "21", label: "Punjab" },
      { value: "22", label: "Rajasthan" },
      { value: "23", label: "Sikkim" },
      { value: "24", label: "Tamil Nadu" },
      { value: "25", label: "Telangana" },
      { value: "26", label: "Tripura" },
      { value: "27", label: "Uttarakhand" },
      { value: "28", label: "Uttar Pradesh" },
      { value: "29", label: "West Bengal" },
      { value: "30", label: "Andaman & Nicobar Islands" },
      { value: "31", label: "Delhi" },
      { value: "32", label: "Chandigarh" },
      { value: "33", label: "Dadra & Naagar Haveli" },
      { value: "34", label: "Daman & Diu" },
      { value: "35", label: "Lakshadweep" },
      { value: "36", label: "Puducherry" },
    ],
    autoComplete: "state",
    isRequired: true,
    placeholder: "State",
  },
  {
    labelText: "accomodation_required",
    labelFor: "accomodation_required",
    id: "accommodation_required",
    name: "accomodation_required",
    type: "dropdown",
    autoComplete: "",
    isRequired: true,
    placeholder: "Accomadation",
    options: [
      { value: "Y", label: "Yes" },
      { value: "N", label: "No" },
    ],
  },
];

const loginFields = [
  {
    labelText: "Email address",
    labelFor: "email-address",
    id: "email",
    name: "email",
    type: "email",
    autoComplete: "email",
    isRequired: true,
    placeholder: "Email address",
  },
  {
    labelText: "Password",
    labelFor: "password",
    id: "password",
    name: "password",
    type: "password",
    autoComplete: "current-password",
    isRequired: true,
    placeholder: "Password",
  },
];

export const eventOptions = [
  {
    value: "1",
    label: "Athletics",
    category: ["men", "women"],
    teamTypes: [
      "100m",
      "200m",
      "400m",
      "800m",
      "1500m",
      "5000m",
      "4x100m",
      "4x400m",
    ],
  },
  {
    value: "2",
    label: "Badminton",
    category: ["men", "women", "mixed"],
    teamTypes: ["Team"],
  },
  {
    value: "3",
    label: "Basketball",
    category: ["men", "women"],
    teamTypes: ["Team"],
  },
  {
    value: "4",
    label: "Cricket",
    category: "men",
    teamTypes: ["Team"],
  },
  {
    value: "5",
    label: "Football",
    category: ["men", "women"],
    teamTypes: ["Team"],
  },
  {
    value: "6",
    label: "Table Tennis",
    category: ["men", "women"],
    teamTypes: ["Team"],
  },
  {
    value: "7",
    label: "Lawn Tennis",
    category: "men",
    teamTypes: ["Team"],
  },
  {
    value: "8",
    label: "Volleyball",
    category: ["men", "women"],
    teamTypes: ["Team"],
  },
  {
    value: "9",
    label: "Kabaddi",
    category: "men",
    teamTypes: ["Team"],
  },
  {
    value: "10",
    label: "Hockey",
    category: "men",
    teamTypes: ["Team"],
  },
  {
    value: "11",
    label: "Squash",
    category: "men",
    teamTypes: ["Single"],
  },
  {
    value: "12",
    label: "Chess",
    category: "open",
    teamTypes: ["Blitz", "Classical"],
  },
  {
    value: "13",
    label: "BGMI",
    category: "open",
    teamTypes: ["Team"],
    team_id: [
      {
        labelText: "id1",
        labelFor: "id1",
        id: "id1",
        name: "id1",
        type: "text",
        autoComplete: "id1",
        isRequired: true,
        placeholder: " id1",
      },
      {
        labelText: "id2",
        labelFor: "id2",
        id: "id2",
        name: "id2",
        type: "text",
        autoComplete: "id2",
        isRequired: true,
        placeholder: " id2",
      },
      {
        labelText: "id3",
        labelFor: "id3",
        id: "id3",
        name: "id3",
        type: "text",
        autoComplete: "ID",
        isRequired: true,
        placeholder: " id3",
      },
      {
        labelText: "id4",
        labelFor: "id4",
        id: "id4",
        name: "id4",
        type: "text",
        autoComplete: "ID",
        isRequired: true,
        placeholder: " id4",
      },
    ],
  },
  {
    value: "14",
    label: "Valorant",
    category: "open",
    teamTypes: ["Team"],
    team_id: [
      {
        labelText: "id1",
        labelFor: "id1",
        id: "id1",
        name: "id1",
        type: "text",
        autoComplete: "id1",
        isRequired: true,
        placeholder: " id1",
      },
      {
        labelText: "id2",
        labelFor: "id2",
        id: "id2",
        name: "id2",
        type: "text",
        autoComplete: "id2",
        isRequired: true,
        placeholder: " id2",
      },
      {
        labelText: "id3",
        labelFor: "id3",
        id: "id3",
        name: "id3",
        type: "text",
        autoComplete: "ID",
        isRequired: true,
        placeholder: " id3",
      },
      {
        labelText: "id4",
        labelFor: "id4",
        id: "id4",
        name: "id4",
        type: "text",
        autoComplete: "ID",
        isRequired: true,
        placeholder: " id4",
      },
      {
        labelText: "id5",
        labelFor: "id5",
        id: "id5",
        name: "id5",
        type: "text",
        autoComplete: "ID",
        isRequired: true,
        placeholder: " id5",
      },
    ],
  },
  {
    value: "15",
    label: "Clash Royale",
    category: "open",
    teamTypes: ["Team"],
    team_id: [
      {
        labelText: "id1",
        labelFor: "id1",
        id: "id1",
        name: "id1",
        type: "text",
        autoComplete: "ID",
        isRequired: true,
        placeholder: " id1",
      },
    ],
  },
];

export const categoryOptions = ["men", "women", "mixed", "open"];
export const teamTypeOptions = [
  "100m",
  "200m",
  "400m",
  "800m",
  "1500m",
  "5000m",
  "4x100m",
  "4x400m",
  "Team",
  "Single",
];

export { events, signupFields, loginFields };
